# Minimal training configuration without callbacks

model:
  name: "DQN"
  save_name: "minimal"
  load_model: false
  use_policy_kwargs: false

environment:
  game_size: 15
  fast_game: true
  use_frame_stack: false
  n_stack: 4
  n_envs: 4

training:
  multiplicator: 3.0
  verbose: 1
  progress_bar: false  # Disable SB3 default progress bar

callbacks:
  enabled: false  # Disable all callbacks
  use_progress: false
  use_curriculum: false
  use_metrics: false
  use_save: false
  curriculum_start: 10
  curriculum_end: 20
  save_freq: 50000

logging:
  log_dir: "logs"
  model_dir: "models"
