# Production training configuration for final models

model:
  name: "PPO"
  save_name: "production"
  load_model: false
  use_policy_kwargs: true

environment:
  game_size: 20
  fast_game: true
  use_frame_stack: true
  n_stack: 4
  n_envs: 8

training:
  multiplicator: 20.0  # Long training for production
  verbose: 2
  progress_bar: true

callbacks:
  enabled: true
  use_progress: true
  use_curriculum: true  # Enable for production
  use_metrics: true     # Enable for production
  use_save: true
  curriculum_start: 15
  curriculum_end: 25
  save_freq: 100000     # Save less frequently for long training

logging:
  log_dir: "logs"
  model_dir: "models"
