# Configuration for RL Snake Training

# Model Configuration
model:
  name: "PPO"  # PPO, DQN, A2C
  save_name: ""
  load_model: false
  use_policy_kwargs: false

# Environment Configuration  
environment:
  game_size: 15
  fast_game: true
  use_frame_stack: false
  n_stack: 4
  n_envs: 5

# Training Configuration
training:
  multiplicator: 5.0
  verbose: 2
  progress_bar: true

# Callbacks Configuration
callbacks:
  enabled: true
  use_progress: true # custom progress bar
  use_curriculum: false
  use_metrics: false
  use_save: true
  curriculum_start: 10
  curriculum_end: 20
  save_freq: 50000

# Logging Configuration
logging:
  log_dir: "logs"
  model_dir: "models"
