# Configuration for RL Snake Training

# Model Configuration
model:
  model_type: "PPO" # PPO, DQN, A2C
  save_name: "PPO.zip"
  load_model: false
  use_policy_kwargs: true

# Environment Configuration
environment:
  game_size: 16
  fast_game: true
  use_frame_stack: false
  n_stack: 4
  n_envs: 5

# Training Configuration
training:
  total_timesteps: 100_000
  eval_interval: 20_000
  verbose: 1
  progress_bar: false
  multiplicator: 5
  device: "cpu"

# Callbacks Configuration
callbacks:
  enabled: true
  use_progress: true # custom progress bar
  use_curriculum: true # dynamic curriculum learning

# Logging Configuration
logging:
  log_dir: "logs"
  model_dir: "models"
